const salesData = [
  {
    image: "/assets/imgs/FSImgs/image1.png",
    name: "Kabir Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/FSImgs/image3.png",
    name: "Chidi Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/FSImgs/image4.png",
    name: "Zadok Chair",
    slashPrice: "110",
    prevPrice: "180",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/FSImgs/image5.png",
    name: "Lanre Chair",
    slashPrice: "110",
    prevPrice: "170",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/FSImgs/image6.png",
    name: "Ezra Chair",
    slashPrice: "100",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/FSImgs/image6.png",
    name: "Ezra Chair",
    slashPrice: "100",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/FSImgs/image6.png",
    name: "Ezra Chair",
    slashPrice: "100",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
];

const BSProdData = [
  {
    image: "/assets/imgs/BSPImgs/image1.png",
    name: "Kabir Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/BSPImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/BSPImgs/image3.png",
    name: "Chidi Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/BSPImgs/image4.png",
    name: "Zadok Chair",
    slashPrice: "110",
    prevPrice: "180",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/BSPImgs/image5.png",
    name: "Lanre Chair",
    slashPrice: "110",
    prevPrice: "170",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/BSPImgs/image6.png",
    name: "Ezra Chair",
    slashPrice: "100",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
];

const products = [
  {
    image: "/assets/imgs/BSPImgs/image1.png",
    name: "Kabir Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
  },
  {
    image: "/assets/imgs/BSPImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
  },
  {
    image: "/assets/imgs/BSPImgs/image3.png",
    name: "Chidi Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "table",
  },
  {
    image: "/assets/imgs/BSPImgs/image4.png",
    name: "Zadok Chair",
    slashPrice: "110",
    prevPrice: "180",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
  },
  {
    image: "/assets/imgs/BSPImgs/image5.png",
    name: "Lanre Chair",
    slashPrice: "110",
    prevPrice: "170",
    rating: "",
    badgeValue: "-20%",
    category: "table",
  },
  {
    image: "/assets/imgs/BSPImgs/image6.png",
    name: "Ezra Chair",
    slashPrice: "100",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "table",
  },
  {
    image: "/assets/imgs/FSImgs/image1.png",
    name: "Kabir Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "table",
  },
  {
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
  },
];

export { salesData, BSProdData, products };

// &#36;
