const salesData = [
  {
    image: "/assets/imgs/FSImgs/image1.png",
    name: "Kabir Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/FSImgs/image3.png",
    name: "Chidi Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/FSImgs/image44.png",
    name: "Zadok Chair",
    slashPrice: "110",
    prevPrice: "180",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/FSImgs/image5.png",
    name: "Lanre Chair",
    slashPrice: "110",
    prevPrice: "170",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/FSImgs/image6.png",
    name: "Ezra Chair",
    slashPrice: "100",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/FSImgs/image6.png",
    name: "Ezra Chair",
    slashPrice: "100",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/FSImgs/image6.png",
    name: "Ezra Chair",
    slashPrice: "100",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
];

const BSProdData = [
  {
    image: "/assets/imgs/BSPImgs/image1.png",
    name: "Kabir Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/BSPImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/BSPImgs/image3.png",
    name: "Chidi Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/BSPImgs/image4.png",
    name: "Zadok Chair",
    slashPrice: "110",
    prevPrice: "180",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/BSPImgs/image5.png",
    name: "Lanre Chair",
    slashPrice: "110",
    prevPrice: "170",
    rating: "",
    badgeValue: "-20%",
  },
  {
    image: "/assets/imgs/BSPImgs/image6.png",
    name: "Ezra Chair",
    slashPrice: "100",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
  },
];

const products = [
  {
    id: 1,
    image: "/assets/imgs/BSPImgs/image1.png",
    name: "Kabir Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 2,
    image: "/assets/imgs/BSPImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 3,
    image: "/assets/imgs/BSPImgs/image3.png",
    name: "Chidi Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "table",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 4,
    image: "/assets/imgs/BSPImgs/image4.png",
    name: "Zadok Chair",
    slashPrice: "110",
    prevPrice: "180",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 5,
    image: "/assets/imgs/BSPImgs/image5.png",
    name: "Lanre Chair",
    slashPrice: "110",
    prevPrice: "170",
    rating: "",
    badgeValue: "-20%",
    category: "table",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 6,
    image: "/assets/imgs/BSPImgs/image6.png",
    name: "Ezra Chair",
    slashPrice: "100",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "table",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 7,
    image: "/assets/imgs/FSImgs/image1.png",
    name: "Kabir Chair",
    slashPrice: "120",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "table",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 8,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 9,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 10,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 11,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 12,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 13,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 14,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 15,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 16,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 17,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 18,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 19,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 20,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 21,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 22,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
  {
    id: 23,
    image: "/assets/imgs/FSImgs/image2.png",
    name: "Asara Chair",
    slashPrice: "110",
    prevPrice: "160",
    rating: "",
    badgeValue: "-20%",
    category: "chair",
     description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit provident est quo officia sed blanditiis autem minima maxime aut assumenda, molestias eveniet voluptate nobis a laborum doloribus non odio sapiente?"
  },
];

export { salesData, BSProdData, products };

// &#36;
